'use strict';
const _mod___Socket_index = require('./Socket/index');
const makeWASocket = _mod___Socket_index.default !== undefined ? _mod___Socket_index.default : _mod___Socket_index;
const _star____WAProto_index = require('../WAProto/index');
Object.keys(_star____WAProto_index).forEach(k => { if (k !== 'default') Object.defineProperty(exports, k, { get: () => _star____WAProto_index[k], enumerable: true }); });
const _star___Utils_index = require('./Utils/index');
Object.keys(_star___Utils_index).forEach(k => { if (k !== 'default') Object.defineProperty(exports, k, { get: () => _star___Utils_index[k], enumerable: true }); });
const _star___Types_index = require('./Types/index');
Object.keys(_star___Types_index).forEach(k => { if (k !== 'default') Object.defineProperty(exports, k, { get: () => _star___Types_index[k], enumerable: true }); });
const _star___Defaults_index = require('./Defaults/index');
Object.keys(_star___Defaults_index).forEach(k => { if (k !== 'default') Object.defineProperty(exports, k, { get: () => _star___Defaults_index[k], enumerable: true }); });
const _star___WABinary_index = require('./WABinary/index');
Object.keys(_star___WABinary_index).forEach(k => { if (k !== 'default') Object.defineProperty(exports, k, { get: () => _star___WABinary_index[k], enumerable: true }); });
const _star___WAM_index = require('./WAM/index');
Object.keys(_star___WAM_index).forEach(k => { if (k !== 'default') Object.defineProperty(exports, k, { get: () => _star___WAM_index[k], enumerable: true }); });
const _star___WAUSync_index = require('./WAUSync/index');
Object.keys(_star___WAUSync_index).forEach(k => { if (k !== 'default') Object.defineProperty(exports, k, { get: () => _star___WAUSync_index[k], enumerable: true }); });
const _re___Socket_dugong = require('./Socket/dugong');
exports.Dugong = _re___Socket_dugong.Dugong;
exports.makeWASocket = makeWASocket;
exports.default = makeWASocket;
module.exports = Object.assign(exports.default, exports);
//# sourceMappingURL=index.js.map